Repository AY2425S1-CS2103T-W11-3/tp, pull requests merged in 2024-11, with the labels that each got.

#182 Update UG for help and tracksubject
  docs/UserGuide.md
  docs/images/tracksubject.png
Labels: priority.Medium

#201 Edit sort command to allow sorting by yearGroup, and other small changes
  src/main/java/seedu/academyassist/logic/commands/AddSubjectCommand.java
  src/main/java/seedu/academyassist/logic/commands/FilterCommand.java
  src/main/java/seedu/academyassist/logic/commands/SortCommand.java
  src/main/java/seedu/academyassist/logic/parser/SortCommandParser.java
  src/main/java/seedu/academyassist/model/AcademyAssist.java
  src/main/java/seedu/academyassist/model/Model.java
  src/main/java/seedu/academyassist/model/ModelManager.java
  src/main/java/seedu/academyassist/model/filter/FilterParam.java
  src/main/java/seedu/academyassist/model/person/UniquePersonList.java
  src/main/java/seedu/academyassist/model/sort/SortParam.java
  src/test/data/JsonSerializableAcademyAssistTest/typicalPersonsAcademyAssist.json
  src/test/java/seedu/academyassist/logic/commands/AddCommandTest.java
  src/test/java/seedu/academyassist/logic/commands/AddSubjectCommandTest.java
  src/test/java/seedu/academyassist/logic/commands/FilterCommandTest.java
  src/test/java/seedu/academyassist/logic/commands/SortCommandIntegrationTest.java
  src/test/java/seedu/academyassist/logic/commands/SortCommandTest.java
  src/test/java/seedu/academyassist/logic/parser/AddSubjectCommandParserTest.java
  src/test/java/seedu/academyassist/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/academyassist/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/academyassist/testutil/TypicalPersons.java
Labels: priority.High

#196 Add Close Subject Statistics Window by Keyboard Shortcut
  src/main/java/seedu/academyassist/ui/TrackSubjectWindow.java
  src/main/resources/view/TrackSubjectWindow.css
  src/main/resources/view/TrackSubjectWindow.fxml
Labels: type.Enhancement, priority.Low

#186 Update user guide for edit command
  docs/UserGuide.md
Labels: priority.Medium

#207 Fix name validation to only accept alphabets
  src/main/java/seedu/academyassist/model/person/Name.java
  src/test/java/seedu/academyassist/model/person/NameTest.java
Labels: type.Enhancement

#221 Add new test cases for year group parameter
  src/test/java/seedu/academyassist/model/person/YearGroupTest.java
Labels: type.Task, priority.High

#184 Make studentId case insensitive
  src/main/java/seedu/academyassist/logic/commands/AddCommand.java
  src/main/java/seedu/academyassist/logic/commands/EditCommand.java
  src/main/java/seedu/academyassist/model/AcademyAssist.java
  src/main/java/seedu/academyassist/model/Model.java
  src/main/java/seedu/academyassist/model/ModelManager.java
  src/main/java/seedu/academyassist/model/ReadOnlyAcademyAssist.java
  src/main/java/seedu/academyassist/model/person/Person.java
  src/main/java/seedu/academyassist/model/person/StudentId.java
  src/main/java/seedu/academyassist/model/util/SampleDataUtil.java
  src/main/java/seedu/academyassist/storage/JsonSerializableAcademyAssist.java
  src/test/java/seedu/academyassist/logic/commands/AddCommandTest.java
  src/test/java/seedu/academyassist/logic/commands/AddSubjectCommandTest.java
  src/test/java/seedu/academyassist/model/AcademyAssistTest.java
  src/test/java/seedu/academyassist/testutil/TypicalPersons.java
Labels: type.Enhancement, severity.Low, alpha-bug

#222 Update error message for student id
  src/main/java/seedu/academyassist/logic/commands/DeleteCommand.java
  src/main/java/seedu/academyassist/logic/commands/DetailCommand.java
  src/main/java/seedu/academyassist/logic/commands/EditCommand.java
Labels: priority.Medium, alpha-bug

#218 Update GUI for person card
  src/main/java/seedu/academyassist/model/person/Name.java
  src/main/java/seedu/academyassist/ui/PersonCard.java
  src/main/java/seedu/academyassist/ui/TrackSubjectWindow.java
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/TrackSubjectWindow.fxml
Labels: type.Enhancement, priority.Medium

#206 Add more subject for addsubjectAdd subject
  src/main/java/seedu/academyassist/model/person/Subject.java
  src/main/java/seedu/academyassist/model/person/SubjectEnum.java
  src/test/java/seedu/academyassist/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/academyassist/model/person/SubjectTest.java
Labels: type.Task, priority.Low

#229 Fix edit command year group issue
  src/main/java/seedu/academyassist/logic/parser/EditCommandParser.java
Labels: priority.High, severity.High, alpha-bug

#230 Standardise formatting for help messages for all commands #Closes 158
  src/main/java/seedu/academyassist/logic/commands/AddCommand.java
  src/main/java/seedu/academyassist/logic/commands/AddSubjectCommand.java
  src/main/java/seedu/academyassist/logic/commands/DeleteCommand.java
  src/main/java/seedu/academyassist/logic/commands/DetailCommand.java
  src/main/java/seedu/academyassist/logic/commands/FilterCommand.java
  src/main/java/seedu/academyassist/logic/commands/FindCommand.java
  src/main/java/seedu/academyassist/logic/commands/SortCommand.java
Labels: priority.Medium

#231 Update add subject to fix person card issue
  src/main/java/seedu/academyassist/model/AcademyAssist.java
  src/test/java/seedu/academyassist/model/AcademyAssistTest.java
Labels: priority.Medium, severity.Low, alpha-bug

#232 Update predicate to allow partial match for find command
  src/main/java/seedu/academyassist/commons/util/StringUtil.java
  src/test/java/seedu/academyassist/commons/util/StringUtilTest.java
Labels: type.Enhancement, priority.Medium, alpha-bug

#241 Update restrictions on name and phone
  src/main/java/seedu/academyassist/model/person/Name.java
  src/main/java/seedu/academyassist/model/person/Phone.java
  src/test/java/seedu/academyassist/model/person/NameTest.java
  src/test/java/seedu/academyassist/model/person/PhoneTest.java
Labels: type.Enhancement, priority.Medium, severity.Low

#244 Fix track window size
  src/main/java/seedu/academyassist/ui/PersonDetailWindow.java
  src/main/java/seedu/academyassist/ui/TrackSubjectWindow.java
  src/main/resources/view/PersonDetailWindow.css
  src/main/resources/view/TrackSubjectWindow.css
  src/main/resources/view/TrackSubjectWindow.fxml
Labels: type.Bug, alpha-bug

#247 Fix error in StudentId display
  src/main/java/seedu/academyassist/logic/commands/AddSubjectCommand.java
  src/main/java/seedu/academyassist/logic/commands/DeleteCommand.java
  src/main/java/seedu/academyassist/logic/commands/DetailCommand.java
  src/main/java/seedu/academyassist/logic/commands/EditCommand.java
  src/main/java/seedu/academyassist/model/person/StudentId.java
Labels: type.Bug, alpha-bug

#251 Update user guide
  docs/UserGuide.md
  docs/images/add.png
  docs/images/addsubject.png
  docs/images/clear.png
  docs/images/delete.png
  docs/images/detail.png
  docs/images/edit.png
  docs/images/filter.png
  docs/images/find.png
  docs/images/list.png
  docs/images/sort.png
  docs/images/tracksubject.png
  src/main/java/seedu/academyassist/logic/commands/EditCommand.java
  src/main/java/seedu/academyassist/model/person/Name.java
  src/test/java/seedu/academyassist/logic/commands/AddSubjectCommandTest.java
Labels: priority.High

#250 Update restriction on names to allow special characters
  src/main/java/seedu/academyassist/logic/parser/CliSyntax.java
  src/main/java/seedu/academyassist/model/person/Email.java
  src/main/java/seedu/academyassist/model/person/Name.java
  src/test/java/seedu/academyassist/logic/parser/AddSubjectCommandParserTest.java
  src/test/java/seedu/academyassist/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/academyassist/model/person/EmailTest.java
  src/test/java/seedu/academyassist/model/person/NameTest.java
  src/test/java/seedu/academyassist/model/person/PersonTest.java
Labels: type.Enhancement

#254 Update gui, developer guide and user guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram-Logic.puml
  docs/diagrams/UndoSequenceDiagram-Model.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/CommitActivityDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/StorageClassDiagram.png
  docs/images/Ui.png
  docs/images/UiClassDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram-Model.png
  src/main/java/seedu/academyassist/model/person/Address.java
  src/main/resources/view/BlueTheme.css
Labels: type.Task, priority.Medium

#255 Update user guide
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#334 Fix rejecting valid input and incorrect ui text
  src/main/java/seedu/academyassist/logic/Messages.java
  src/main/java/seedu/academyassist/logic/parser/FindCommandParser.java
  src/test/java/seedu/academyassist/logic/parser/FindCommandParserTest.java
Labels: type.Bug, severity.High

#335 Update UG to fix bugs highlighted in PED
  docs/UserGuide.md
Labels: type.Enhancement, type.Bug, type.documentation

#339 Fix fails silently bug when student id count exceeds limit
  src/main/java/seedu/academyassist/logic/Messages.java
  src/main/java/seedu/academyassist/logic/commands/AddCommand.java
  src/main/java/seedu/academyassist/model/AcademyAssist.java
  src/main/java/seedu/academyassist/model/Model.java
  src/main/java/seedu/academyassist/model/ModelManager.java
  src/main/java/seedu/academyassist/storage/JsonSerializableAcademyAssist.java
  src/test/java/seedu/academyassist/logic/commands/AddCommandTest.java
  src/test/java/seedu/academyassist/logic/commands/AddSubjectCommandTest.java
Labels: type.Bug, severity.High

#338 Update User guide
  docs/UserGuide.md
  docs/images/UiOverview.png
  docs/index.md
  src/main/java/seedu/academyassist/logic/parser/DetailCommandParser.java
Labels: type.documentation

#358 Update the Instructions for Manual Testing in DG
  docs/DeveloperGuide.md
Labels: priority.High, type.documentation, documentation.dg
