Repository AY2425S1-CS2103T-W11-3/tp, pull requests merged in 2024-10, with the labels that each got.

#16 Add Wei Jin's photo
  docs/images/cweijin.png
Labels: type.Task

#12 Add Joanne's Photo
  src/main/resources/images/joannehing.png
Labels: type.Task

#18 Update Wei Jin's info in AboutUs page
  docs/AboutUs.md
Labels: type.Task

#23 Update Ethan's info in AboutUs page
  docs/AboutUs.md
Labels: type.Task

#26 Move the image location
  docs/images/joannehing.png
Labels: type.Task

#39 Update team details in the AboutUs page
  README.md
  docs/AboutUs.md
  docs/images/Ui.png
Labels: type.Task, priority.Low

#37 Update readme
  README.md
  docs/images/Ui.png
Labels: type.Epic, priority.Medium

#29 Remove Dummy Value
  docs/AboutUs.md
Labels: type.Task

#44 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: priority.High

#58 Make help window scrollable with details of functions
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: type.Task, priority.High

#60 Add first version of sort command Closes #59
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/sort/SortParam.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High

#67 Update find command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: type.Story, priority.Medium

#78 Update add class feature to accept multiple classes/subjects
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Subject.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedSubject.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#81 Update colour coding
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/Logo.png
  src/main/resources/view/BlueTheme.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
Labels: type.Task, priority.High

#82 Update the GUI for help window
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/Logo.png
  src/main/resources/view/BlueTheme.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
Labels: type.Task, priority.Medium

#84 update font
  src/main/resources/view/BlueTheme.css
  src/main/resources/view/HelpWindow.css
Labels: type.Task, priority.Low

#89 update styling
  src/main/resources/view/BlueTheme.css
  src/main/resources/view/Extensions.css
Labels: type.Enhancement, priority.Low

#92 Update edit command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/person/IdMatchesPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
Labels: type.Story, priority.Medium

#100 Update delete command
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/model/person/IcMatchesPredicate.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalIcs.java
Labels: type.Story, priority.Medium

#101 Refractor code to match current product
  src/main/java/seedu/academyassist/ui/HelpWindow.java
Labels: type.Epic, priority.Medium

#105 update gui and jar file naming format
  build.gradle
  src/main/java/seedu/academyassist/logic/commands/AddCommand.java
Labels: type.Task, priority.Low

#109 Update error message display for edit and sort
  src/main/java/seedu/academyassist/logic/commands/EditCommand.java
  src/main/java/seedu/academyassist/logic/commands/SortCommand.java
Labels: type.Enhancement, priority.Low

#111 Add new fields for student's year group and update ui
  src/main/java/seedu/academyassist/logic/Messages.java
  src/main/java/seedu/academyassist/logic/commands/AddCommand.java
  src/main/java/seedu/academyassist/logic/commands/EditCommand.java
  src/main/java/seedu/academyassist/logic/parser/AddCommandParser.java
  src/main/java/seedu/academyassist/logic/parser/CliSyntax.java
  src/main/java/seedu/academyassist/logic/parser/ParserUtil.java
  src/main/java/seedu/academyassist/model/person/Person.java
  src/main/java/seedu/academyassist/model/person/YearGroup.java
  src/main/java/seedu/academyassist/model/util/SampleDataUtil.java
  src/main/java/seedu/academyassist/storage/JsonAdaptedPerson.java
  src/main/java/seedu/academyassist/ui/PersonCard.java
  src/main/resources/view/BlueTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAcademyAssistTest/duplicatePersonAcademyAssist.json
  src/test/data/JsonSerializableAcademyAssistTest/typicalPersonsAcademyAssist.json
  src/test/java/seedu/academyassist/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/academyassist/model/person/PersonTest.java
  src/test/java/seedu/academyassist/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/academyassist/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/academyassist/testutil/PersonBuilder.java
  src/test/java/seedu/academyassist/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#115 Remove tags and fix test cases
  src/main/java/seedu/academyassist/logic/Messages.java
  src/main/java/seedu/academyassist/logic/commands/AddCommand.java
  src/main/java/seedu/academyassist/logic/commands/EditCommand.java
  src/main/java/seedu/academyassist/logic/parser/AddCommandParser.java
  src/main/java/seedu/academyassist/logic/parser/CliSyntax.java
  src/main/java/seedu/academyassist/logic/parser/EditCommandParser.java
  src/main/java/seedu/academyassist/logic/parser/ParserUtil.java
  src/main/java/seedu/academyassist/model/person/Person.java
  src/main/java/seedu/academyassist/model/tag/Tag.java
  src/main/java/seedu/academyassist/model/util/SampleDataUtil.java
  src/main/java/seedu/academyassist/storage/JsonAdaptedPerson.java
  src/main/java/seedu/academyassist/storage/JsonAdaptedTag.java
  src/test/data/JsonSerializableAcademyAssistTest/duplicatePersonAcademyAssist.json
  src/test/data/JsonSerializableAcademyAssistTest/typicalPersonsAcademyAssist.json
  src/test/java/seedu/academyassist/logic/LogicManagerTest.java
  src/test/java/seedu/academyassist/logic/commands/CommandTestUtil.java
  src/test/java/seedu/academyassist/logic/commands/EditCommandTest.java
  src/test/java/seedu/academyassist/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/academyassist/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/academyassist/logic/parser/ParserUtilTest.java
  src/test/java/seedu/academyassist/model/AcademyAssistTest.java
  src/test/java/seedu/academyassist/model/person/PersonTest.java
  src/test/java/seedu/academyassist/model/person/SubjectTest.java
  src/test/java/seedu/academyassist/model/person/UniquePersonListTest.java
  src/test/java/seedu/academyassist/model/tag/TagTest.java
  src/test/java/seedu/academyassist/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/academyassist/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/academyassist/testutil/PersonBuilder.java
  src/test/java/seedu/academyassist/testutil/PersonUtil.java
  src/test/java/seedu/academyassist/testutil/TypicalPersons.java
Labels: type.Task, priority.Medium

#118 Add Subject as Enumeration & validate subject input
  src/main/java/seedu/academyassist/logic/commands/EditCommand.java
  src/main/java/seedu/academyassist/logic/parser/AddClassCommandParser.java
  src/main/java/seedu/academyassist/model/person/Subject.java
  src/main/java/seedu/academyassist/model/person/SubjectEnum.java
  src/main/java/seedu/academyassist/model/util/SampleDataUtil.java
  src/main/java/seedu/academyassist/storage/JsonAdaptedPerson.java
  src/main/java/seedu/academyassist/storage/JsonAdaptedSubject.java
  src/main/java/seedu/academyassist/ui/PersonCard.java
  src/test/data/JsonSerializableAcademyAssistTest/typicalPersonsAcademyAssist.json
  src/test/java/seedu/academyassist/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/academyassist/testutil/PersonBuilder.java
  src/test/java/seedu/academyassist/testutil/PersonUtil.java
  src/test/java/seedu/academyassist/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#120 Add student id field & implement automatic student id generation
  src/main/java/seedu/academyassist/logic/Messages.java
  src/main/java/seedu/academyassist/logic/commands/AddClassCommand.java
  src/main/java/seedu/academyassist/logic/commands/AddCommand.java
  src/main/java/seedu/academyassist/logic/commands/DeleteCommand.java
  src/main/java/seedu/academyassist/logic/commands/EditCommand.java
  src/main/java/seedu/academyassist/logic/parser/AddClassCommandParser.java
  src/main/java/seedu/academyassist/logic/parser/AddCommandParser.java
  src/main/java/seedu/academyassist/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/academyassist/logic/parser/EditCommandParser.java
  src/main/java/seedu/academyassist/logic/parser/ParserUtil.java
  src/main/java/seedu/academyassist/logic/parser/SortCommandParser.java
  src/main/java/seedu/academyassist/model/AcademyAssist.java
  src/main/java/seedu/academyassist/model/Model.java
  src/main/java/seedu/academyassist/model/ModelManager.java
  src/main/java/seedu/academyassist/model/ReadOnlyAcademyAssist.java
  src/main/java/seedu/academyassist/model/person/Person.java
  src/main/java/seedu/academyassist/model/person/StudentId.java
  src/main/java/seedu/academyassist/model/person/StudentIdMatchesPredicate.java
  src/main/java/seedu/academyassist/model/person/UniquePersonList.java
  src/main/java/seedu/academyassist/model/util/SampleDataUtil.java
  src/main/java/seedu/academyassist/storage/JsonAdaptedPerson.java
  src/main/java/seedu/academyassist/storage/JsonSerializableAcademyAssist.java
  src/main/java/seedu/academyassist/ui/HelpWindow.java
  src/main/java/seedu/academyassist/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAcademyAssistTest/duplicatePersonAcademyAssist.json
  src/test/data/JsonSerializableAcademyAssistTest/typicalPersonsAcademyAssist.json
  src/test/java/seedu/academyassist/logic/LogicManagerTest.java
  src/test/java/seedu/academyassist/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/academyassist/logic/commands/AddCommandTest.java
  src/test/java/seedu/academyassist/logic/commands/CommandTestUtil.java
  src/test/java/seedu/academyassist/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/academyassist/logic/commands/EditCommandTest.java
  src/test/java/seedu/academyassist/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/academyassist/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/academyassist/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/academyassist/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/academyassist/logic/parser/ParserUtilTest.java
  src/test/java/seedu/academyassist/model/AcademyAssistTest.java
  src/test/java/seedu/academyassist/model/person/PersonTest.java
  src/test/java/seedu/academyassist/model/person/SubjectTest.java
  src/test/java/seedu/academyassist/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/academyassist/testutil/PersonBuilder.java
  src/test/java/seedu/academyassist/testutil/TypicalPersons.java
  src/test/java/seedu/academyassist/testutil/TypicalStudentIds.java
  src/test/resources/view/UiPartTest/validFileWithFxRoot.fxml
Labels: type.Enhancement, priority.Medium

#121 Add FilterCommand
  README.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/academyassist/logic/commands/AddCommand.java
  src/main/java/seedu/academyassist/logic/commands/FilterCommand.java
  src/main/java/seedu/academyassist/logic/parser/AcademyAssistParser.java
  src/main/java/seedu/academyassist/logic/parser/CliSyntax.java
  src/main/java/seedu/academyassist/logic/parser/FilterCommandParser.java
  src/main/java/seedu/academyassist/logic/parser/ParserUtil.java
  src/main/java/seedu/academyassist/model/filter/FilterParam.java
  src/main/java/seedu/academyassist/model/person/PersonInYearPredicate.java
  src/main/java/seedu/academyassist/model/person/PersonTakeSubjectPredicate.java
  src/main/java/seedu/academyassist/ui/HelpWindow.java
  src/test/java/seedu/academyassist/logic/commands/AddClassCommandTest.java
Labels: priority.High

#125 Modify addc to add multiple classes fix #124
  src/main/java/seedu/academyassist/logic/commands/AddClassCommand.java
  src/main/java/seedu/academyassist/logic/parser/AddClassCommandParser.java
  src/main/java/seedu/academyassist/model/AcademyAssist.java
  src/main/java/seedu/academyassist/model/Model.java
  src/main/java/seedu/academyassist/model/ModelManager.java
  src/test/java/seedu/academyassist/logic/commands/AddCommandTest.java
Labels: priority.High

#137 Enable assertions in the project
  build.gradle
Labels: type.Task, priority.Low

#132 Add Person Detail Window
  src/main/java/seedu/academyassist/logic/commands/CommandResult.java
  src/main/java/seedu/academyassist/logic/commands/DetailCommand.java
  src/main/java/seedu/academyassist/logic/commands/ExitCommand.java
  src/main/java/seedu/academyassist/logic/commands/HelpCommand.java
  src/main/java/seedu/academyassist/logic/parser/AcademyAssistParser.java
  src/main/java/seedu/academyassist/logic/parser/DetailCommandParser.java
  src/main/java/seedu/academyassist/ui/MainWindow.java
  src/main/java/seedu/academyassist/ui/PersonDetailWindow.java
  src/main/resources/view/PersonDetailWindow.css
  src/main/resources/view/PersonDetailWindow.fxml
  src/test/java/seedu/academyassist/logic/commands/CommandResultTest.java
  src/test/java/seedu/academyassist/logic/commands/ExitCommandTest.java
  src/test/java/seedu/academyassist/logic/commands/HelpCommandTest.java
Labels: type.Story, type.Task, priority.High

#131 Add tests for AddClassCommand
  src/main/java/seedu/academyassist/logic/commands/AddClassCommand.java
  src/test/java/seedu/academyassist/logic/commands/AddClassCommandTest.java
  src/test/java/seedu/academyassist/logic/parser/AddClassCommandParserTest.java
Labels: priority.High

#140 Update UndoRedoState 0, 1 and 2 UML Diagram
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  src/test/java/seedu/academyassist/logic/commands/DetailCommandTest.java
Labels: type.Task, priority.Medium

#146 Update ModelClassDiagram
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Task

#128 Add track class size feature
  docs/UserGuide.md
  docs/_sass/minima/_base.scss
  src/main/java/seedu/academyassist/logic/Logic.java
  src/main/java/seedu/academyassist/logic/LogicManager.java
  src/main/java/seedu/academyassist/logic/commands/CommandResult.java
  src/main/java/seedu/academyassist/logic/commands/ExitCommand.java
  src/main/java/seedu/academyassist/logic/commands/HelpCommand.java
  src/main/java/seedu/academyassist/logic/commands/TrackSubjectCommand.java
  src/main/java/seedu/academyassist/logic/parser/AcademyAssistParser.java
  src/main/java/seedu/academyassist/ui/HelpWindow.java
  src/main/java/seedu/academyassist/ui/MainWindow.java
  src/main/java/seedu/academyassist/ui/TrackSubjectWindow.java
  src/main/resources/view/TrackSubjectWindow.css
  src/main/resources/view/TrackSubjectWindow.fxml
  src/test/java/seedu/academyassist/logic/commands/CommandResultTest.java
  src/test/java/seedu/academyassist/logic/commands/ExitCommandTest.java
  src/test/java/seedu/academyassist/logic/commands/HelpCommandTest.java
Labels: type.Epic, priority.High

#148 Add close detail window by keyboard shortcut
  docs/UserGuide.md
  src/main/java/seedu/academyassist/ui/HelpWindow.java
  src/main/java/seedu/academyassist/ui/PersonDetailWindow.java
  src/main/resources/view/PersonDetailWindow.css
  src/main/resources/view/PersonDetailWindow.fxml
Labels: type.Task, priority.Medium

#154 Add tests for add command parser
  src/test/java/seedu/academyassist/logic/commands/CommandTestUtil.java
  src/test/java/seedu/academyassist/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/academyassist/testutil/TypicalPersons.java
Labels: type.Enhancement

#156 Add tests for help, tracksubject and sort functions
  build.gradle
  src/main/java/seedu/academyassist/logic/commands/SortCommand.java
  src/main/java/seedu/academyassist/model/person/SubjectEnum.java
  src/test/java/seedu/academyassist/logic/commands/CommandResultTest.java
  src/test/java/seedu/academyassist/logic/commands/HelpCommandTest.java
  src/test/java/seedu/academyassist/logic/commands/SortCommandIntegrationTest.java
  src/test/java/seedu/academyassist/logic/commands/SortCommandTest.java
  src/test/java/seedu/academyassist/logic/commands/TrackSubjectCommandTest.java
  src/test/java/seedu/academyassist/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/academyassist/model/person/SubjectTest.java
Labels: priority.Medium
